name: textgrad_medical_qa_optimize
repo:
  name: textgrad
  url: "https://github.com/zou-group/textgrad"
  commit: bf5b0c5
  env:
    OPENAI_API_KEY: "${env:OPENAI_API_KEY}"
papers: [yuksekgonul2024textgrad]
category: pathology
description: >
  Optimize answers to multiple-choice medical questions using TextGrad.
  Each question is improved at test-time through textual gradients,
  guided by an objective (e.g. "Make the answer concise and accurate"). 
arguments:
  - name: csv_path
    description: "Path to a CSV file containing columns: 'index', 'question', 'objective'"
    type: str
  - name: backward_engine
    description: The model used to compute textual gradients (e.g., 'gpt-4o')
    type: str
  - name: forward_engine
    description: The model used to generate initial zero-shot answers (e.g., 'gpt-3.5-turbo')
    type: str
  - name: starting_system_prompt
    description: "System prompt to guide the LLM behavior"
    type: str
  - name: optimizer_constraint
    description: "Constraint string that specifies the required answer format"
    type: str
returns:
  - name: optimized_answers
    description: "A list of optimized answers, each ending with 'Answer: $LETTER'"
    type: list
example:
  arguments:
    - name: csv_path
      value: /mount/input/sample_0.csv
    - name: backward_engine
      value: gpt-4o
    - name: forward_engine
      value: gpt-4o
    - name: starting_system_prompt
      value: |
        You are ChatGPT, a large language model trained by OpenAI, based on the GPT-4 architecture.
        Knowledge cutoff: 2023-12
        Current date: 2024-04-01
    - name: optimizer_constraint
      value: |
        You must end your answer with a separate line like: 'Answer: A', 'Answer: B', 'Answer: C', or 'Answer: D'. 
        Do NOT include any additional explanation or diagnosis after 'Answer: $LETTER'.
  mount:
    - source: sample_0.csv
      target: sample_0.csv
test_invocations:
  - name: sample_0
    arguments:
      - name: csv_path
        value: /mount/input/sample_0.csv
      - name: backward_engine
        value: gpt-4o
      - name: forward_engine
        value: gpt-4
      - name: starting_system_prompt
        value: |
          You are ChatGPT, a large language model trained by OpenAI, based on the GPT-4 architecture.
          Knowledge cutoff: 2023-12
          Current date: 2024-04-01
      - name: optimizer_constraint
        value: |
          You must end your answer with a separate line like: 'Answer: A', 'Answer: B', 'Answer: C', or 'Answer: D'. 
          Do NOT include any additional explanation or diagnosis after 'Answer: $LETTER'.
    mount:
      - source: sample_0.csv
        target: sample_0.csv
  - name: sample_1
    arguments:
      - name: csv_path
        value: /mount/input/sample_1.csv
      - name: backward_engine
        value: gpt-4o
      - name: forward_engine
        value: gpt-4
      - name: starting_system_prompt
        value: |
          You are ChatGPT, a large language model trained by OpenAI, based on the GPT-4 architecture.
          Knowledge cutoff: 2023-12
          Current date: 2024-04-01
      - name: optimizer_constraint
        value: |
          You must end your answer with a separate line like: 'Answer: A', 'Answer: B', 'Answer: C', or 'Answer: D'. 
          Do NOT include any additional explanation or diagnosis after 'Answer: $LETTER'.
    mount:
      - source: sample_1.csv
        target: sample_1.csv
  - name: sample_2
    arguments:
      - name: csv_path
        value: /mount/input/sample_2.csv
      - name: backward_engine
        value: gpt-4o
      - name: forward_engine
        value: gpt-4
      - name: starting_system_prompt
        value: |
          You are ChatGPT, a large language model trained by OpenAI, based on the GPT-4 architecture.
          Knowledge cutoff: 2023-12
          Current date: 2024-04-01
      - name: optimizer_constraint
        value: |
          You must end your answer with a separate line like: 'Answer: A', 'Answer: B', 'Answer: C', or 'Answer: D'. 
          Do NOT include any additional explanation or diagnosis after 'Answer: $LETTER'.
    mount:
      - source: sample_2.csv
        target: sample_2.csv

