name: cobra_extract_features # Name of the task. Should correspond to the name of the folder.
requires: cuda
repo:
  name: COBRA # Name of the repository.
  url: "https://github.com/KatherLab/COBRA" # URL of the repository.
  commit: null # Commit hash of the repository (optional, default is the latest commit). It is recommended to use a specific commit to ensure reproducibility.
  # branch: main # Branch of the repository (optional)
  env:
    # Here, you can specify environment variables that should be available for installing the repository or running the task.
    # The format is key: value, where value is a string that can include variables from the local environment.
    # You may also leave this empty if the repository does not require any tokens/secrets.
    HF_TOKEN: "${env:HF_TOKEN}"  # Example environment variable that sets HF_TOKEN to the local environment variable HF_TOKEN.
papers: [lenz2024cobra] # List of papers that this task is based on. Papers are specified by their IDs in the papers.bib file.
category: pathology # Category of the task.
description: Perform feature extraction on an input image using COBRA. The provided tile features have 1.0 mpp (224 microns / 224 px per patch).  # Description of the task. This should be 1-3 sentences in length, explaining to the LLM what this tool should do.
arguments:
  - name: output_dir
    description: Path to the output folder where the features will be saved
    type: str
  - name: input_dir
    description: Path to the input folder containing the tile features
    type: str
returns:
  - name: num_processed_slides
    description: The number of slides that were processed
    type: int
example:
  arguments:
    - name: output_dir
      value: /mount/output/cobra_features
    - name: input_dir
      value: /mount/input/TCGA-CRC-Virchow2-features-10x
  mount:
    # In this section, you can specify files or folders that should be mounted from the data directory to the container (at "/mount/input" in the container).
    # Each mount is a dictionary with the keys "source" and "target", where "source" is the path to the file or folder in the data directory and "target" is the path to the file or folder in the container.
    # For example, the following line mounts the file "TUM-TCGA-ACRLPPQE.tif" from the data directory to the container, placing it at the path "/mount/input/TUM-TCGA-ACRLPPQE.tif" in the container.
    - source: TCGA-CRC-Virchow2-features-10x
      target: TCGA-CRC-Virchow2-features-10x
    - source: crc-wsi
      target: crc-wsi
test_invocations:
  # Below, we define test invocations for the task.
  # Each test invocation is a dictionary with the keys "name", "arguments", and "mount", like the example invocation above (with the addition of the "name" key).
  # The test invocations can be used in the unit tests to check that the task is working as expected.
  # Below, we define 3 test invocations for the task, named "tif", "png", and "jpg". 
  # It is recommended that you define at least 3 test invocations (of course, you can choose any names you want).
  - name: crc
    arguments:
      - name: output_dir
        value: /mount/output/cobra_features
      - name: input_dir
        value: /mount/input/TCGA-CRC-Virchow2-features-10x
    mount:
      - source: TCGA-CRC-Virchow2-features-10x
        target: TCGA-CRC-Virchow2-features-10x
      - source: crc-wsi
        target: crc-wsi
  # - name: h5
  #   arguments:
  #     - name: output_features
  #       value: /mount/input/TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.png
  #   mount:
  #     - source: TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.png
  #       target: TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.png
  # - name: jpg
  #   arguments:
  #     - name: input_image
  #       value: /mount/input/TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.jpg
  #   mount:
  #     - source: TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.jpg
  #       target: TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.jpg