name: conch_extract_features
repo:
  name: CONCH
  url: "https://github.com/mahmoodlab/CONCH"
  commit: 171f2be
  env:
    HF_TOKEN: "${env:HF_TOKEN}"  # required for downloading models
papers: [lu2024conch]
category: pathology
requires: cuda
description: Perform feature extraction on an input image using CONCH.
arguments:
  - name: input_image
    description: Path to the input image
    type: str
returns:
  - name: features
    description: The feature vector extracted from the input image, as a list of floats
    type: list
example:
  arguments:
    - name: input_image
      value: /mount/input/TUM-TCGA-ACRLPPQE.tif
  mount:
    - source: TUM-TCGA-ACRLPPQE.tif
      target: TUM-TCGA-ACRLPPQE.tif
test_invocations:
  - name: tif
    arguments:
      - name: input_image
        value: /mount/input/MUC/MUC-TCGA-ACCPKIPN.tif
    mount:
      - source: MUC-TCGA-ACCPKIPN.tif
        target: MUC/MUC-TCGA-ACCPKIPN.tif
  - name: png
    arguments:
      - name: input_image
        value: /mount/input/TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.png
    mount:
      - source: TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.png
        target: TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.png
  - name: jpg
    arguments:
      - name: input_image
        value: /mount/input/TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.jpg
    mount:
      - source: TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.jpg
        target: TCGA-BRCA_patch_TCGA-BH-A0DE-01Z-00-DX1.64A0340A-8146-48E8-AAF7-4035988B9152.jpg

