name: cyvcf2_count_alterations
repo:
  name: cyvcf2
  url: "https://github.com/brentp/cyvcf2" 
  commit: 541ab16 
  branch: main 
  env: []
papers: [pedersen2017cyvcf2] 
category: genomics_proteomics
requires: cpu 
description: Use cyvcf2 to parse through VCF file containing detected sequence variants to identify the number of single nucleotide polymorphisms (SNPs) from a specific reference nucleotide to a specific alternate nucleotide.
arguments:
  - name: input_vcf
    description: Path to the input VCF file
    type: str
  - name: reference_nucleotide
    description: The reference nucleotide to compare against ("A", "C", "G", or "T")
    type: str
  - name: alternate_nucleotide
    description: The alternate nucleotide to compare against ("A", "C", "G", or "T")
    type: str
returns:
  - name: num_snps
    description: The number of SNPs that are altered from reference `reference_nucleotide` to `alternate_nucleotide`.
    type: int
example:
  arguments:
    - name: input_vcf
      value: /mount/input/SRR2058984_zc.vcf
    - name: reference_nucleotide
      value: "A"
    - name: alternate_nucleotide
      value: "C"
  mount:
    - source: SRR2058984_zc.vcf
      target: SRR2058984_zc.vcf
test_invocations:
  - name: SRR2058985
    arguments:
      - name: input_vcf
        value: /mount/input/SRR2058985_zc.vcf
      - name: reference_nucleotide
        value: "A"
      - name: alternate_nucleotide
        value: "T"
    mount:
      - source: SRR2058985_zc.vcf
        target: SRR2058985_zc.vcf
  - name: SRR2058987
    arguments:
      - name: input_vcf
        value: /mount/input/SRR2058987_zc.vcf
      - name: reference_nucleotide
        value: "T"
      - name: alternate_nucleotide
        value: "C"
    mount:
      - source: SRR2058987_zc.vcf
        target: SRR2058987_zc.vcf
  - name: SRR2058988
    arguments:
      - name: input_vcf
        value: /mount/input/SRR2058988_zc.vcf
      - name: reference_nucleotide
        value: "T"
      - name: alternate_nucleotide
        value: "A"
    mount:
      - source: SRR2058988_zc.vcf
        target: SRR2058988_zc.vcf
  - name: SRR2058989
    arguments:
      - name: input_vcf
        value: /mount/input/SRR2058989_zc.vcf
      - name: reference_nucleotide
        value: "T"
      - name: alternate_nucleotide
        value: "G"
    mount:
      - source: SRR2058989_zc.vcf
        target: SRR2058989_zc.vcf
